spring:
  application:
    name: financial-control
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /v1
application:
  security:
    api-key: ${API_KEY}
management:
  endpoint:
    health:
      group:
        database:
          include: db
          show-components: always
          show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: financial-control-api
